{
  "metadata": {
    "name": "productpage",
    "namespace": "demo-japan",
    "labels": {},
    "annotations": {},
    "description": null,
    "disable": null
  },
  "spec": {
    "domains": [
      "ves-io-df0b903c-6cdc-453d-ab44-788b1092ae89.ac.vh.ves.io"
    ],
    "http": {
      "dns_volterra_managed": null
    },
    "advertise_on_public_default_vip": {},
    "default_route_pools": [
      {
        "pool": {
          "namespace": "demo-japan",
          "name": "productpage"
        },
        "weight": 1,
        "endpoint_subsets": {}
      }
    ],
    "routes": null,
    "cors_policy": null,
    "waf": {
      "namespace": "demo-japan",
      "name": "test-waf"
    },
    "add_location": null,
    "no_challenge": {},
    "more_option": null,
    "user_identification": null,
    "disable_rate_limit": {},
    "malicious_user_mitigation": null,
    "waf_exclusion_rules": null,
    "blocked_clients": null,
    "trusted_clients": null,
    "ddos_mitigation_rules": null,
    "service_policies_from_namespace": {},
    "round_robin": {}
  },
  "resource_version": null
}