kind: Deployment
apiVersion: apps/v1
metadata:
  name: details
  labels:
    app: details
    version: v1
  annotations:
    ves.io/virtual-sites: demo-japan/middle-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
        - name: details
          image: istio/examples-bookinfo-details-v1:1.9.0
          ports:
            - containerPort: 9080
              protocol: TCP
