kind: Service
apiVersion: v1
metadata:
  name: productpage
  labels:
    app: productpage
    svc: productpage
  annotations:
    ves.io/virtual-sites: demo-japan/front-site
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app: productpage
  type: ClusterIP

