kind: Deployment
apiVersion: apps/v1
metadata:
  name: productpage
  labels:
    app: productpage
    version: v1
  annotations:
    ves.io/virtual-sites: demo-japan/front-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
        - name: productpage
          image: istio/examples-bookinfo-productpage-v1:latest
          ports:
            - containerPort: 9080
              protocol: TCP
