kind: Service
apiVersion: v1
metadata:
  name: ratings
  labels:
    app: ratings
    svc: ratings
  annotations:
    ves.io/virtual-sites: demo-japan/middle-site
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app: ratings
  type: ClusterIP
