kind: Deployment
apiVersion: apps/v1
metadata:
  name: ratings
  labels:
    app: ratings
    version: v1
  annotations:
    ves.io/virtual-sites: demo-japan/middle-site
    ves.io/workload-flavor: large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
        - name: ratings
          image: istio/examples-bookinfo-ratings-v1:latest
          ports:
            - containerPort: 9080
              protocol: TCP
