kind: Service
apiVersion: v1
metadata:
  name: reviews
  labels:
    app: reviews
    svc: reviews
  annotations:
    ves.io/virtual-sites: demo-japan/backend-site
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app: reviews
  type: ClusterIP
