kind: Deployment
apiVersion: apps/v1
metadata:
  name: reviews-v3
  labels:
    app: reviews
    version: v3
  annotations:
    ves.io/virtual-sites: demo-japan/backend-site
    ves.io/workload-flavor: large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
        - name: reviews
          image: ruiwang14/istio-book-info-reviews-v3:1.0
          ports:
            - containerPort: 9080
              protocol: TCP